### ISSUE TITLE
CrownEvent can add non existing player 

### ISSUE THREAD

**Issue by Tunous** [Yonom/BotBits#1]
The initial crown message can contain user ID of a player that collected the crown and left world. Because of that when we connect to a world CrownEvent adds new player with that ID to the Players class.

**Comment by Yonom** [comment]
Well, yes, the player will have a null username, and it's `Connected` will be set to false. This is indeed the expected behavior (how else would you want to know the - even invalid - id the game sends you?)

Once the documentation is done, this will be properly documented. Usually, you would want to check for "Connected" before doing anything in a CrownEvent callback.

There is a slight memory leak due to this, but since this is a one time thing, it is not worth introducing weak referenced objects.
